### ISSUE TITLE
Envelope Node Gain parameter may be redundant/confusing

### ISSUE THREAD

**Issue by imf2304236** [ychaw/noise-nodes#11]
With respect to the current logic, this parameter is technically an attack level. So, I would recommend renaming it as such or just removing it entirely and just setting it to a static value of 1.

If the parameter remains as a Gain value, then I would expect the internal Sustain value to be set with respect to this gain value, i.e. 

`node.gain.linearRampToValueAtTime(this.state.sustain.absValue * targetGain, endTimes[1]);`.

**Comment by ychaw** [comment]
fixed in 3efbb458aecbc577cd7038b2b795cd833948a9cb
